### ISSUE TITLE
Bower Rails v. Rails Assets

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lae-blacklight#105]
Consider using https://github.com/rharriso/bower-rails over rails assets. This lets you directly use a bower.json file directly to define js dependencies for a Rails project. I kind of think this approach has more legs that dealing with Rails Assets https://rails-assets.org/ which proxies bower packages to bundler.

**Comment by jpstroop** [comment]
It certainly sounds cleaner.

**Comment by kevinreiss** [comment]
Just using plain old bower now. See #118.
