### ISSUE TITLE
Masonry Error Upon Upgrade to Rails 4.2.2

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lae-blacklight#108]
@axapu see the https://github.com/pulibrary/lae-blacklight/tree/rails_4_2_2 branch. After update to rails 4.2.2 the masonry grid no longer seems to work. This branch is running at http://lae-dev.princeton.edu/ if you want to check it out. Also #106 is still a valid issue still working if you are going to check this one out.

**Comment by axapu** [comment]
Should we try to use the blacklight-gallery gem for the masonry view?

**Comment by kevinreiss** [comment]
Yes, I think that would be worth trying. I'd forgotten they'd added that feature.

**Comment by kevinreiss** [comment]
We will probably need to refactor what was done with the gallery views.

**Comment by kevinreiss** [comment]
@axapu Check out the results after this change 28c029b19b427060a4d827b491283dcf1e60f0d3.

**Comment by kevinreiss** [comment]
REsolved.
