### ISSUE TITLE
Canvas aren't getting labels

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/lae-blacklight#13]
Technically a pul-store issue, but afraid it may drown over there :frowning:.

**Comment by kevinreiss** [comment]
This seems correct now. They were missing on this view? 

http://lae-dev.princeton.edu/catalog/00028.jsonld

**Comment by kevinreiss** [comment]
@jpstroop what labels are missing on the canvas?

**Comment by kevinreiss** [comment]
The URLs for the "page" objects in the jsonld http://lae.princeton.edu/catalog/008zp.jsonld resolve to a 404.
