### ISSUE TITLE
Schedule Guest User Cleanup Task. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lae-blacklight#134]
See https://github.com/pulibrary/orangelight/issues/787

**Comment by hackmastera** [comment]
the referenced ticket mentioned the possibility of using ansible; do we mostly use ansible for crons? another option would be the whenever gem; if we're deploying to multiple boxes you can constrain the cron to just one in capistrano

**Comment by escowles** [comment]
We haven't done any cron jobs for Plum/Figgy.  But it seems like taking advantage of Sidekiq would be nice — and probably make it easier to let users kick this off if they wanted to do it on-demand.

**Comment by hackmastera** [comment]
didn't realize you could do this with just sidekiq. that sounds like a great idea.

**Comment by escowles** [comment]
I think we will still need cron or something to kick off the Sidekiq job — I'm mostly just saying that we probably want both scheduled and on-demand options for housekeeping tasks like this.

**Comment by jrgriffiniii** [comment]
Following an initial test of the cron tasks within the production environment, it appears that these jobs should consume less than 1 hour of time to properly clean the database.  Hence, I'm going to proceed with leaving these to run nightly at 22:00:00-05:00.

**Comment by jrgriffiniii** [comment]
Addressed within organizational Ansible Playbooks using https://github.com/pulibrary/princeton_ansible/pull/93
