### ISSUE TITLE
Change order of facets

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/lae-blacklight#136]
To: 

Format/Genre
Date of Publication
Place of Publication 
Subject: Topic
Subject: Geographic
Language

**Comment by hackmastera** [comment]
Assuming this ticket is just about order, they will be:

Genre
Date Created
Geographic Origin
Subject
Geographic Subject
Language

If these aren't equivalent to the above, or if the labels should also be changed, please let me know!
