### ISSUE TITLE
Fonts of subject/category

### ISSUE THREAD

**Issue by escowles** [pulibrary/lae-blacklight#195]
Font size of subject categories seems to be larger than before, since the subject categories don't appear on one line. Thus, many separations occur; e.g., Politics and govern-ment, Protest move-ments, Political cam-paigns, etc. In addition, there seem to be two different fonts on the new site (Times New Roman and Arial?).

**Comment by tpendragon** [comment]
The big issue here seems to be that the facet_count width is being set to 77px for some reason, where it's not set at all for `lae.princeton.edu`

**Comment by escowles** [comment]
That's happening in the main blacklight CSS (https://github.com/projectblacklight/blacklight/blob/master/app/assets/stylesheets/blacklight/_facets.scss#L117) — I suspect because 5em of width works better when you have facet counts in the thousands.

I think we can safely dial it back quite a bit.
