### ISSUE TITLE
fix formatting of login page

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lae-blacklight#213]
the login area should be contained within the customary content area.

To reproduce:
* do a search.
* click on "search history"
* click "save"

current screenshot: 
![screen shot 2017-11-16 at 2 16 35 pm](https://user-images.githubusercontent.com/845363/32911113-2fdf87d6-cad9-11e7-8acd-4cbb7adb1b73.png)

**Comment by hackmastera** [comment]
Actually this may be the "saved searches" page; not the login page per se

see
![screen shot 2017-11-16 at 2 21 50 pm](https://user-images.githubusercontent.com/845363/32911220-84a61c08-cad9-11e7-80f3-bae28141fe0e.png)

**Comment by hackartisan** [comment]
this looks correct now
