### ISSUE TITLE
Reorganize subnav in header

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/lae-blacklight#216]
In needing a spot for controls for #140 and uncovering bugs #214 and #215 I believe we need to reorganize the subnav a bit to make everything work / fit. Here's a mockup.
https://docs.google.com/drawings/d/1WEJVm4eflQYRI8O4dyNFS0sdSGTVKoPWFBwRTwGQ8tU/edit?usp=sharing

![lae-blacklight subnav reorg](https://user-images.githubusercontent.com/845363/32917446-37d9e576-caed-11e7-9b11-233914ad63f9.jpg)

**Comment by escowles** [comment]
That looks good to me — grouping the user-specific functionality at the top corner is nice.
