### ISSUE TITLE
LAE Sync Error

### ISSUE THREAD

**Issue by escowles** [pulibrary/lae-blacklight#261]
Some records in Box 68 and 81 are not syncing to LAE correctly (they show up in search results, but you get a "Something Went Wrong" error when trying to view them, e.g.:
https://lae.princeton.edu/catalog/bd85bc12-df4f-437e-8cc9-1b55136a5e39?locale=en

**Comment by jrgriffiniii** [comment]
I could not reproduce any parsing errors when using some JSON-LD representations from Figgy as fixtures, and items from 68 (https://figgy.princeton.edu/catalog/50a1a026-0226-46b6-8783-ad5597998691) and 81 (https://figgy.princeton.edu/catalog/parent/d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d/413c0dfe-2db2-462c-b782-23506e433bf3) seem to be rendering in search results (https://lae.princeton.edu/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=NGC+BOCAS+LIT+FEST+2013) and as items (https://lae.princeton.edu/catalog/e8990e29-8ea5-4e43-ad9e-bd02d6780444?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1609%2C-194%2C4287%2C3875).

**Comment by escowles** [comment]
I re-saved all of the Figgy items, which did not appear to fix the problem.  But I think that is probably because the Solr autocommit had not happened.  Now, I am not seeing any errors with any of these objects.  I'll check back with Luiza and Gabrielle to make sure they are not seeing errors any longer.

**Comment by escowles** [comment]
I have emailed Gabrielle to confirm whether this is resolved — I'm going to close this ticket and we can re-open or create new tickets as appropriate if there are more problems.
