### ISSUE TITLE
Error page displaying when trying to navigate to LAE site

### ISSUE THREAD

**Issue by kelea99** [pulibrary/lae-blacklight#288]
Reported by gabrielle winkler and reproduced by me. @escowles had no problem in private window - thinks maybe it's auth-related. 
<img width="1440" alt="Screen Shot 2020-07-14 at 9 29 19 AM" src="https://user-images.githubusercontent.com/45043014/87431844-32304c80-c5b5-11ea-8e46-bcc97c2db9b2.png">

**Comment by eliotjordan** [comment]
@kayiwa and @tpendragon retired and replaced old lae server. Issue is currently resolved.
