### ISSUE TITLE
Update Node.js to 14.y.z (Fermium LTS)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/lae-blacklight#293]
Please see pulibrary/princeton_ansible#1315 for reference

**Comment by jrgriffiniii** [comment]
When invoking `bundle install`, I am repeatedly encountering errors to the effect of the following:

```bash
An error occurred while installing libv8 (3.16.14.19), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.19' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  therubyracer was resolved to 0.12.3, which depends on
    libv8
```

This may simply be related to the C compilation tools which are used by default within the macOS Big Sur release 11.2.3 environment.

**Comment by hackartisan** [comment]
Reopening until prod is provisioned with the right node version.

**Comment by jrgriffiniii** [comment]
I have just successfully tested https://github.com/pulibrary/princeton_ansible/pull/2769 against the `staging` environment. I shall test this against `production` now.

**Comment by jrgriffiniii** [comment]
This was also successfully tested against the `production` environment.
