### ISSUE TITLE
Upgrade to Solr 8

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/lae-blacklight#294]
We expect this process will be the same as used for Cicognara: https://github.com/pulibrary/cicognara-rails/issues/474 and that checklist can be copied over to this issue once it's been validated.

Relevant PRs:

https://github.com/pulibrary/pul_solr/pull/237
https://github.com/pulibrary/princeton_ansible/pull/1748

**Comment by bess** [comment]
This appears to have been done already, via this PR: https://github.com/pulibrary/princeton_ansible/commit/a71d5d459192c518a4dc37610995d881ead19f64
