### ISSUE TITLE
Records and Faceting in LAE site not showing bulk of Genres in collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/lae-blacklight#350]
From Stakeholders: While testing the restored Genre Facet, they realized the numbers for Genre in the faceting did not match up with Figgy.  The Genre is also non displaying for all items in the individual item record in LAE. 

>  "The vast majority of the records are not displaying that field and therefore aren’t counted if one tries to filter by Genre. Notice that when you open the Genre facet only about 2,000 out of the 21,000+ total are counted." - Fernando"

To test:

- I found an item in LAE that was not displaying the Genre ( Guia Varadero.).
- I went in to figgy, found the record ([Link here](https://figgy.princeton.edu/catalog/parent/0f65e5c1-6b25-460d-a8f8-f19bd610fa3a/599cdbc3-588c-4805-96cc-3599cadea39b))  and re-selected the genre in edit and re-saved the item. 
- I went back to LAE and confirmed that this did, indeed fix the LAE display. the genre now is present (LAE [LINK HERE](https://lae.princeton.edu/catalog/599cdbc3-588c-4805-96cc-3599cadea39b?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1219%2C-213%2C4691%2C4241))

Maybe the site just needs a reindex? or something on the figgy side for the entire ephemera project for LAE?

**Comment by hackartisan** [comment]
probably a reindex

**Comment by tpendragon** [comment]
I'm building a fresh index in a tmux pane on lae1 into the lae-prod2 collection as per the README directions.

**Comment by kelea99** [comment]
Looks good to me. Just pinged stakeholders to confirm

**Comment by kelea99** [comment]
Fix confirmed. Closing.
