### ISSUE TITLE
LAE site not pulling in new completions for LAE ephemera in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/lae-blacklight#356]
Reported by Gabrielle W. LAE has not been pulling in new completions for Ephemera from figgy for about a month.  Does LAE need a reindex? She said this has happened in the past. Ill look for closed tickets to see if the fix was noted

**Comment by kelea99** [comment]
Old ticket that sounds similar: **https://github.com/pulibrary/lae-blacklight/issues/330**

**Comment by tpendragon** [comment]
The queues weren't made - redeploying LAE got that going, and then I kicked off a reindex on `lae1`.
