### ISSUE TITLE
Provision Jammy VMs

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lae-blacklight#365]
# Reasoning

We need to upgrade all our boxes to Jammy; we're starting to be unable to get apt packages, etc.

# Boxes to Migrate

These are the names of the existing boxes. We can change the names to use current conventions, suggestions inline.

## Staging
`lae-staging1` => migrate to `lae-staging2`?

## Production
`lae1` => migrate to `lae-prod1`
`lae2` => migrate to `lae-prod2`

**Comment by acozine** [comment]
The old LAE prod boxes have:
- 2 CPUs
- 8 GB of memory
- 40 GB hard disk

**Comment by acozine** [comment]
Three new Jammy VMs are ready to be used!

**Comment by tpendragon** [comment]
We're reopening these, but just so we can keep track of doing the provisioning of these now that they're made.
