### ISSUE TITLE
Migrate Solr Staging from lib-solr8-staging to lib-solr8-d-staging

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/lae-blacklight#374]
Sub-ticket of https://github.com/pulibrary/princeton_ansible/issues/4666

**Comment by hackartisan** [comment]
Everything is hooked up correctly and the env var was changed in https://github.com/pulibrary/princeton_ansible/commit/bfbd403331ccc1ea27107e27f9409670d5335d65. However the reindex hit a network error so the index isn't fully populated. I've restarted the index process on the staging box.

**Comment by hackartisan** [comment]
reindex finished.
