### ISSUE TITLE
Update the contact email address

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lae-blacklight#387]
### What maintenance needs to be done?

contact form email destination needs to be reconfigured (currently goes to a gmail address)

discovered when trying to test https://github.com/pulibrary/lae-blacklight/pull/386

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- contact form should submit to an institutional address, preferably one monitored by a group.

### Acceptance criteria
 - [ ] the appropriate email address is identified
 - [ ] the contact form is configured to submit to the appropriate email address

### First step
search the codebase for gmail to see where to change the configuration

**Comment by tpendragon** [comment]
This should go to `digital-library@princeton.libanswers.com`
