### ISSUE TITLE
Add Dartmouth logo to lower left of site and edit English/Spanish/Portuguese text on Home Page

### ISSUE THREAD

**Issue by kelea99** [pulibrary/lae-blacklight#388]
## Current display

- See main site screenshots below (4 total)

### Update brief introductory text near the top of the homepage in the following way. Also please update the Spanish and Portuguese language iterations of the page. All changes are highlighted below. 

- The Digital Archive of Latin American and Caribbean Ephemera is a steadily growing repository containing a previously unavailable subset of Princeton’s [Latin American Ephemera Collection](http://libguides.princeton.edu/laec), materials from our partner libraries, as well as newly acquired materials being digitized and added on an ongoing basis.
-     https://lae.princeton.edu/?locale=en

- El Archivo Digital de Efímera de América Latina y el Caribe es un repositorio en constante crecimiento que contiene un subconjunto de la [Colección de Documentos Efímeros de América Latina](http://libguides.princeton.edu/laec) de Princeton que no estaba disponible anteriormente, materiales provenientes de otras bibliotecas colaboradoras, así como materiales recién adquiridos que se digitalizan y agregan de forma continua.
-     https://lae.princeton.edu/?locale=es

- O Arquivo Digital de Documentos Efêmeros da América Latina e Caribe é um repositório em constante crescimento que contém uma parte da Coleção de Documentos Efêmeros da América Latina da Universidade de Princeton até agora nunca disponível, materiais provenientes de outras bibliotecas colaboradoras, além de materiais recém-adquiridos que são digitalizados e adicionados de forma contínua.
-     https://lae.princeton.edu/?locale=pt-BR

### Add the attached Dartmough logo to the LAE homepage, placed at the bottom left of the page to the right of PUL’s and CLIR’s logos. 

- If the provided logo doesn’t work for any reason, let Fernando know.
- Provided link: 
![Most Popular Logo](https://github.com/pulibrary/lae-blacklight/assets/45043014/3d514d08-c3fb-42c2-903f-5326fc4d640e)

## Reason for High Priority / Workcycle Labels

Ideally needed for Panel 8 presentations by Fernando and Jill Baron (Dartmouth) at [SALALM Conference session ](https://tulane.app.box.com/s/1ooholtprscvud107q8ovdno3j34sall)starting at 8:30am CDT (in New Orleans) on Monday, 6/10: 

- Ephemera Visible : “Not So Much Ephemeral as Invisible: Latin American Reproductive Rights and Women’s Health Pamphlets in the Dartmouth Libraries,” Jill Baron, Dartmouth College

- “Democratizing Access to Ephemera Together: Initial Steps Towards a Collaborative Future,” Fernando Acosta-Rodríguez, Princeton University

Moderator/Rapporteur: Fernando Acosta-Rodríguez, Princeton University

## Acceptance criteria

- [x] I can successfully use this feature with Voice Over in Safari.
- [x] #394
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

## Screenshots
<img width="1512" alt="Screenshot 2024-05-30 at 6 13 16 AM" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/6b0504c1-633a-4b07-84fc-59d23b87b181">
<img width="1512" alt="Screenshot 2024-05-30 at 6 14 03 AM" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/f597d8a9-96c5-4309-ab61-e458407b5386">
<img width="1512" alt="Screenshot 2024-05-30 at 6 13 56 AM" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/cb61dc27-a383-4d14-a4e5-a0fe415b64d6">
<img width="1512" alt="Screenshot 2024-05-30 at 6 13 46 AM" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/291321eb-ddb2-44c7-ab9a-29f0c9c75432">

## First Step

Wireframe the placement of the Dartmouth logo.

**Comment by tpendragon** [comment]
Kim's gonna do the mockups.

**Comment by kelea99** [comment]
## Mockups (Three Total)

### Option 01 (Left Aligned with Princeton Crest)
<img width="1512" alt="Option_01_Dartmouth-logo" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/11c863d4-2c5f-4011-b74d-318e41b447e4">

### Option 02 (Right Aligned)
<img width="1512" alt="Option_02_Dartmouth-logo" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/fadb53d2-5a15-43e4-9da3-312d39bea9a6">

### Option 03 (Left Aligned with Text)
<img width="1512" alt="Option_03_Dartmouth-logo" src="https://github.com/pulibrary/lae-blacklight/assets/45043014/5503bac1-e96f-4c70-8c2d-b74fdcde52cc">

**Comment by kelea99** [comment]
heard from Fernando! 

> I like the second one. Let's not add any text for now. Once the [other] collaboration is in place, we can contribute a separate contributors page with accompanying text. Thank you very much.

So: Proceed with Option 02,  Right Aligned, for the Dartmouth Libraries logo.

**Comment by hackartisan** [comment]
What if we put the princeton & dartmouth logos on the left and then moved the other two (funding agency) logos to the right? That might provide a more balanced look.

**Comment by sdellis** [comment]
## Design Pass #2 
@kelea99 After looking at the [Ganiza Project attributions in the footer](https://geniza.princeton.edu/en/), it seemed best to draw a distinction between the types of contributors (content vs. financial contributions). This is a mock-up that emulates that approach. Let us know what you and Fernando think. 

![DartmouthLogo](https://github.com/pulibrary/lae-blacklight/assets/609368/a3ce7c82-0b27-4cb1-b8c0-7578ec13eb61)

**Comment by sdellis** [comment]
Here's a second option with the contributor attributions side by side. Note that this design will wrap at smaller screen sizes so that the logos and text will stack, similar to the mock-up in the comment above this one. 

![DartmouthLogo2](https://github.com/pulibrary/lae-blacklight/assets/609368/ac9bfffe-2439-49e5-ab34-1e2eaf9d3749)

**Comment by kelea99** [comment]
@sdellis , from Fernando and Gabrielle:

> Since CLIR and LARRP grants ended years ago, I’m now thinking that we should remove their logos and the accompanying text from the LAE homepage (an acknowledgment will still be available in the About page).
> 
> So, I would eliminate the top half from the following option and keep the bottom half (Princeton logo left and Dartmouth logo to its right.

**Comment by tpendragon** [comment]
We're gonna do this one:

https://private-user-images.githubusercontent.com/609368/341488978-a3ce7c82-0b27-4cb1-b8c0-7578ec13eb61.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTcwNDksIm5iZiI6MTcyMjQ1Njc0OSwicGF0aCI6Ii82MDkzNjgvMzQxNDg4OTc4LWEzY2U3YzgyLTBiMjctNGNiMS1iOGMwLTc1NzhlYzEzZWI2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQyMDEyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWJkNDk4MWE0Mzc3NjVlNTJmOGU1YTA1OTBiM2EzMzUwYzdhNDVhY2Y0N2IyNGQwOGIyNWM4OTUzZGFkZjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._d1eFlX4sh3TsRv7968DKJ_6I2_jFsScZnq6rzrsdGk

We're not sure if it's okay to just remove CLIR and LARRP's logos, but if it turns out it's fine then that layout still works.

**Comment by kelea99** [comment]
Let stakeholders know, @AminEdZare and @sdellis ! Thank you!
