### ISSUE TITLE
Range Limit (date facet) isn't working

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/lae-blacklight#398]
The range limit functionality broke as part of the upgrade to Rails 7.1

![Screen Shot 2024-09-17 at 1 06 41 PM](https://github.com/user-attachments/assets/be81e483-413f-4604-a515-3c2082405173)

Error: https://app.honeybadger.io/projects/53813/faults/111429053/01J80R6QFVZX8X2RE7EYXS047C?q=-context.maintenance_window%3A%22true%22+occurred.after%3A%228+days+ago%22 

## Acceptance Criteria

- [ ] Clicking "Search", then "Date Created" provides a facet where I can select dates to facet to, and doing so works.
- [ ] There's a screenshot in a PR of the fixed range limit.

## Sudden Priority Justification

This is a feature that broke during our Rails upgrade which leaves the app in an unstable state. We should fix it as soon as we can.

## First Step

Look at what it used to look like before the Rails 7.1 patch.

It might be worth poking around information for the range limit.

Look at blacklight-range-limit and see what might be missing in LAE to get it to work.

**Comment by eliotjordan** [comment]
Start and end dates are being reversed:
https://app.honeybadger.io/projects/53813/faults/111429053

![Screenshot 2024-09-23 at 2 09 32 PM](https://github.com/user-attachments/assets/5793a010-7af5-403c-9fcd-4664f704ac4c)

I've tried a number of things (see linked draft PR) and I haven't figured out what's going on. I suspect there is a data issue on the Figgy/indexing/Solr side.

**Comment by eliotjordan** [comment]
It was one incorrect date range value.
`206-2018` in this record: https://figgy.princeton.edu/catalog/9eebc57f-3162-4325-9685-9b2cc5419186

Dates all have to have the same number of digits or be indexed into a another field type.
https://github.com/projectblacklight/blacklight_range_limit?tab=readme-ov-file#note-on-solr-field-types

I fixed this record and the date ranges are appearing as normal. If this is a concern in the future we could update the data field type and/or enforce your digit years in Figgy.

![Screenshot 2024-09-23 at 2 44 37 PM](https://github.com/user-attachments/assets/98308425-2625-4819-9ce8-0242923e64dc)
![Screenshot 2024-09-23 at 2 44 28 PM](https://github.com/user-attachments/assets/6be942d9-7c22-4be3-ac19-394b04a591a3)
