### ISSUE TITLE
LAE Sneakers nodes are sometimes failing repeatedly, filling up logs

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/lae-blacklight#405]
## Background

We've gotten reports of the disk of some LAE nodes maxing out, causing them to crash. The logs are coming from sneakers, and the log message is the following:

```
Nov 18 15:40:38 lae-prod1 sneakers[41466]: Unexpected error PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'lae_production_queue' in vhost '/': received none but current is the value 'lae_production_queue-retry' of type 'longstr'
```

This is usually because at one point the RabbitMQ queue got created with a dead letter queue defined, but then a node tried to recreate it without one defined. We've tried to fix this before by deleting the RabbitMQ queue and letting it get recreated, but it inevitably breaks again.

We've also noticed that one box always errors, and one box doesn't.

## Acceptance Criteria

- [ ] Sneakers starts and doesn't start crashing.

## First step

Do some investigation. Google the error, check the code to see if there's something weird going on with the dead letter queue. What's the difference between DPUL and LAE's sneakers config? Is there a version difference?

## Sudden Priority Justification

This issue is recurring and pulls us off other stuff, we should fix it.

**Comment by hackartisan** [comment]
the error can be seen in /var/log/syslog

**Comment by hackartisan** [comment]
After deploying I deleted the queues and they go re-created; the logs seem okay now. But since the queues were deleted it seems like we should do a new index, so re-opening this.

**Comment by hackartisan** [comment]
I created a new index and swapped it in. I turned the sneakers workers back on and all the queues are clear.
